baseURL = "https://www.alicegherbison.com/"
defaultContentLanguage = "en"
languageCode = "en"
title = "Alice G Herbison"
disableKinds = ["taxonomy", "taxonomyTerm"]

[params]
	author = "Alice G Herbison"
	description = "Website of Alice G Herbison, user experience designer based in Edinburgh, Scotland."
	tags = "ux, design, html, css, javascript"

[languages]
	[languages.en]
		title = "Alice G Herbison"
		weight = 1
		languageName = "English"

[blackfriday]
 	plainIDAnchors = true
 	hrefTargetBlank = true