baseURL = "https://alicegherbison.com/"
defaultContentLanguage = "en"
languageCode = "en"
title = "Alice G Herbison"
disableKinds = ["taxonomy", "taxonomyTerm"]

[languages]
	[languages.en]
		title = "Alice G Herbison"
		weight = 1
		languageName = "English"